CREATE TABLE usuarios
(
	id INT NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(25) UNIQUE NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	fechaRegistro DATETIME NOT NULL,
	activo TINYINT NOT NULL,
	suscripcion TINYINT NOT NULL,
	PRIMARY KEY(id)
);
