
CREATE TABLE usuarios
(
	id INT NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(25) UNIQUE NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	fechaRegistro DATETIME NOT NULL,
	activo TINYINT NOT NULL,
	suscripcion TINYINT NOT NULL,
	puntos INT NOT NULL,
	avatar INT NOT NULL,
	PRIMARY KEY(id)
);
CREATE TABLE entradas(
	id INT NOT NULL UNIQUE AUTO_INCREMENT,
	autorId INT NOT NULL,
	titulo VARCHAR(255) NOT NULL,
	texto TEXT CHARACTER SET utf8 NOT NULL,
	fecha DATETIME NOT NULL,
	activa TINYINT NOT NULL,
	likes INT NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(autorId)
		REFERENCES usuarios(id)
		ON UPDATE CASCADE
		ON DELETE RESTRICT
);
CREATE TABLE comentarios(
	id INT NOT NULL UNIQUE AUTO_INCREMENT,
	autorId INT NOT NULL,
	entradaId INT NOT NULL,
	titulo VARCHAR(255) NOT NULL,
	texto TEXT CHARACTER SET utf8 NOT NULL,
	fecha DATETIME NOT NULL,
	activa TINYINT NOT NULL,
	likes INT NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(autorId)
		REFERENCES usuarios(id)
		ON UPDATE CASCADE
		ON DELETE RESTRICT,
	FOREIGN KEY(entradaId)
		REFERENCES entradas(id)
		ON UPDATE CASCADE
		ON DELETE RESTRICT

);
CREATE TABLE CURSOS(
	id INT NOT NULL UNIQUE AUTO_INCREMENT,
	autorId INT NOT NULL,
	titulo VARCHAR(255) NOT NULL,
	miniatura TEXT NOT NULL,
	ruta TEXT CHARACTER SET utf8 NOT NULL,
	texto TEXT CHARACTER SET utf8 NOT NULL,
	fecha DATETIME NOT NULL,
	vistas INT NOT NULL,
	PRIMARY KEY(id),
		FOREIGN KEY(autorId)
			REFERENCES usuarios(id)
			ON UPDATE CASCADE
			ON DELETE RESTRICT
);
