
CREATE TABLE usuarios
(
	id INT NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(25) UNIQUE NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	fechaRegistro DATETIME NOT NULL,
	activo TINYINT NOT NULL,
	suscripcion TINYINT NOT NULL,
	puntos INT NOT NULL,
	avatar INT NOT NULL,
	PRIMARY KEY(id)
);
CREATE TABLE entradas(
	id INT NOT NULL UNIQUE AUTO_INCREMENT,
	autorId INT NOT NULL,
	titulo VARCHAR(255) NOT NULL,
	texto TEXT CHARACTER SET utf8 NOT NULL,
	fecha DATETIME NOT NULL,
	activa TINYINT NOT NULL,
	likes INT NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(autorId)
		REFERENCES usuarios(id)
		ON UPDATE CASCADE
		ON DELETE RESTRICT
);
CREATE TABLE comentarios(
	id INT NOT NULL UNIQUE AUTO_INCREMENT,
	autorId INT NOT NULL,
	entradaId INT NOT NULL,
	titulo VARCHAR(255) NOT NULL,
	texto TEXT CHARACTER SET utf8 NOT NULL,
	fecha DATETIME NOT NULL,
	activa TINYINT NOT NULL,
	likes INT NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(autorId)
		REFERENCES usuarios(id)
		ON UPDATE CASCADE
		ON DELETE RESTRICT,
	FOREIGN KEY(entradaId)
		REFERENCES entradas(id)
		ON UPDATE CASCADE
		ON DELETE RESTRICT

);
CREATE TABLE comentariosCursos(
	id INT NOT NULL UNIQUE AUTO_INCREMENT,
	autorId INT NOT NULL,
	cursoId INT NOT NULL,
	texto TEXT CHARACTER SET utf8 NOT NULL,
	fecha DATETIME NOT NULL,
	activa TINYINT NOT NULL,
	likes INT NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(autorId)
		REFERENCES usuarios(id)
		ON UPDATE CASCADE
		ON DELETE RESTRICT,
	FOREIGN KEY(cursoId)
		REFERENCES cursos(id)
		ON UPDATE CASCADE
		ON DELETE RESTRICT
);
CREATE TABLE cursos(
	id INT NOT NULL UNIQUE AUTO_INCREMENT,
	autorId INT NOT NULL,
	titulo VARCHAR(255) NOT NULL,
	miniatura TEXT NOT NULL,
	ruta TEXT CHARACTER SET utf8 NOT NULL,
	texto TEXT CHARACTER SET utf8 NOT NULL,
	fecha DATETIME NOT NULL,
	vistas INT NOT NULL,
	PRIMARY KEY(id),
		FOREIGN KEY(autorId)
			REFERENCES usuarios(id)
			ON UPDATE CASCADE
			ON DELETE RESTRICT
);
CREATE TABLE capitulos(
	id INT NOT NULL UNIQUE AUTO_INCREMENT,
	cursoId INT NOT NULL,
	titulo VARCHAR(255) NOT NULL,
	ruta TEXT CHARACTER SET utf8 NOT NULL,
	fecha DATETIME NOT NULL,
	PRIMARY KEY(id),
		FOREIGN KEY(cursoId)
		REFERENCES cursos(id)
		ON UPDATE CASCADE
		ON DELETE RESTRICT
);
CREATE TABLE programas(
	id INT NOT NULL UNIQUE AUTO_INCREMENT,
	titulo VARCHAR(255) NOT NULL,
	descripcion VARCHAR(255) NOT NULL,
	ruta TEXT CHARACTER SET utf8 NOT NULL,
	fecha DATETIME NOT NULL,
	imagen TEXT NOT NULL,
	PRIMARY KEY(id)
);
CREATE TABLE CNPublicaciones(
id INT NOT NULL UNIQUE AUTO_INCREMENT,
autorId INT NOT NULL,
titulo VARCHAR(255) NOT NULL,
texto TEXT CHARACTER SET utf8 NOT NULL,
imagen TEXT NOT NULL,
estado TINYINT NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY(autorId)
	REFERENCES usuarios(id)
	ON UPDATE CASCADE
	ON DELETE RESTRICT
);
CREATE TABLE TFG(
	idUsuario INT NOT NULL UNIQUE AUTO_INCREMENT,
	x INT NOT NULL,
	y INT NOT NULL
);
CREATE TABLE likesUsuariosEntradas(
	id INT NOT NULL UNIQUE AUTO_INCREMENT,
	idEntrada INT NOT NULL,
	idUsuario INT NOT NULL
);
CREATE TABLE cosasPorHacer(
	id INT NOT NULL UNIQUE AUTO_INCREMENT,
	idUsuario INT NOT NULL,
	actividad VARCHAR(50) NOT NULL,
	fecha DATETIME NOT NULL,
	estado TINYINT NULL,
	tope INT NOT NULL
);
CREATE TABLE agenda(
	id INT NOT NULL UNIQUE AUTO_INCREMENT,
	idUsuario INT NOT NULL,
	actividad VARCHAR(50) NOT NULL,
	estado TINYINT NULL,
	dia VARCHAR(25) NOT NULL,
	mes VARCHAR(25) NOT NULL,
	year INT NOT NULL
);